/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package crimescene;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepu Singla
 */
public class missingvehiclerecords extends javax.swing.JFrame {

    /**
     * Creates new form missingvehiclerecords
     */
    public missingvehiclerecords() {
        initComponents();
        show_user();
    }

    public ArrayList<UserVehicle>userList(String ValToSearch){
    ArrayList<UserVehicle>usersList = new ArrayList<>();
     try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ppdp","root","");
         Statement stmt=con.createStatement();
         //String xx = "SELECT * FROM seniorrecords";
         String xx="SELECT * FROM `vehiclerecords` WHERE CONCAT(`src`,`first_name`,`last_name`,`father_name`,`dob`,`address`,`vehicle_type`,`vehicle_comp`,`vehicle_model`,`vehicle_color`,`license_plate`,`license_id`,`theft_date`,`theft_location`,`contact`)LIKE'%"+ValToSearch+"%'";
          ResultSet rs=stmt.executeQuery(xx);
   
          
          UserVehicle user;
    while(rs.next())
    {
        user=new UserVehicle(rs.getInt("src"),rs.getString("first_name"),rs.getString("last_name"),rs.getString("father_name"),rs.getString("dob"),rs.getString("address"),rs.getString("vehicle_type"),rs.getString("vehicle_comp"),rs.getString("vehicle_model"),rs.getString("vehicle_color"),rs.getString("license_plate"),rs.getString("license_id"),rs.getString("theft_date"),rs.getString("theft_location"),rs.getString("contact"));
        usersList.add(user);
    }
           }
     catch(Exception ex){
         JOptionPane.showMessageDialog(this,ex);
    } 
     return usersList;
}
public void show_user(){
    ArrayList<UserVehicle>list = userList(jTextField1.getText());
  //DefaultTableModel model = (DefaultTableModel)jTable_Display_User.getModel();
    DefaultTableModel model1 = new DefaultTableModel();
    model1.setColumnIdentifiers(new Object[]{"Src","Firstname","Lastname","Father_name","Dob","Address","Vehicle_type","Vehicle_type","Vehicle_comp","Vehicle_model","Vehicle_color","License_id","License_plate","Theft_date","Theft_location","Contact"});
   // DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    Object[]row = new Object[15];
    for(int i=0;i<list.size();i++)
    {
        row[0]=list.get(i).getsrc();
         row[1]=list.get(i).getfirst_name();
         row[2]=list.get(i).getlast_name();
         row[3]=list.get(i).getfather_name();
         row[4]=list.get(i).getdob();
         row[5]=list.get(i).getaddress();
         row[6]=list.get(i).getvehicle_type();
         row[7]=list.get(i).getvehicle_comp();
         row[8]=list.get(i).getvehicle_model();
         row[9]=list.get(i).getvehicle_color();
         row[10]=list.get(i).getlicense_plate();
         row[11]=list.get(i).getlicense_id();
         row[12]=list.get(i).gettheft_date();
        row[13]=list.get(i).gettheft_location();
        row[14]=list.get(i).getcontact();
            model1.addRow(row);
    }
     jTable1.setModel(model1);
}

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(180, 155));
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Src", "Firstname", "Lastname", "Father_name", "Dob", "address", "Vehicle_type", "Vehicle_comp", "Vehicle_model", "Vehicle_color", "License_plate", "License_id", "Theft_date", "Theft_location", "Contact"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1118, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
show_user();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
ppdp p11 = new ppdp();
p11.setVisible(true);
setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(missingvehiclerecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(missingvehiclerecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(missingvehiclerecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(missingvehiclerecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new missingvehiclerecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
